const Discord = require('discord.js');

const mapping = {
    ' ': '   ',
    '0': ':zero:',
    '1': ':one:',
    '2': ':two:',
    '3': ':three:',
    '4': ':four:',
    '5': ':five:',
    '6': ':six:',
    '7': ':seven:',
    '8': ':eight:',
    '9': ':nine:',
    '!': ':grey_exclamation:',
    '?': ':grey_question:',
    '#': ':hash:',
    '*': ':asterisk:',
    'a': ':regional_indicator_a:',
    'b': ':regional_indicator_b:',
    'c': ':regional_indicator_c:',
    'ç': ':regional_indicator_c:',
    'd': ':regional_indicator_d:',
    'e': ':regional_indicator_e:',
    'f': ':regional_indicator_f:',
    'g': ':regional_indicator_g:',
    'ğ': ':regional_indicator_g:',
    'h': ':regional_indicator_h:',
    'ı': ':regional_indicator_i:',
    'i': ':regional_indicator_i:',
    'j': ':regional_indicator_j:',
    'k': ':regional_indicator_k:',
    'l': ':regional_indicator_l:',
    'm': ':regional_indicator_m:',
    'n': ':regional_indicator_n:',
    'o': ':regional_indicator_o:',
    'ö': ':regional_indicator_o:',
    'p': ':regional_indicator_p:',
    'r': ':regional_indicator_r:',
    's': ':regional_indicator_s:',
    'ş': ':regional_indicator_s:',
    't': ':regional_indicator_t:',
    'u': ':regional_indicator_u:',
    'ü': ':regional_indicator_u:',
    'v': ':regional_indicator_v:',
    'y': ':regional_indicator_y:',
    'z': ':regional_indicator_z:',
    'q': ':regional_indicator_q:',
    'w': ':regional_indicator_w:',
    'x': ':regional_indicator_x:',
  //CAPSLOCK
    'A': ':regional_indicator_a:',
    'B': ':regional_indicator_b:',
    'C': ':regional_indicator_c:',
    'Ç': ':regional_indicator_c:',
    'D': ':regional_indicator_d:',
    'E': ':regional_indicator_e:',
    'F': ':regional_indicator_f:',
    'G': ':regional_indicator_g:',
    'Ğ': ':regional_indicator_g:',
    'H': ':regional_indicator_h:',
    'I': ':regional_indicator_i:',
    'İ': ':regional_indicator_i:',
    'J': ':regional_indicator_j:',
    'K': ':regional_indicator_k:',
    'L': ':regional_indicator_l:',
    'M': ':regional_indicator_m:',
    'N': ':regional_indicator_n:',
    'O': ':regional_indicator_o:',
    'Ö': ':regional_indicator_o:',
    'P': ':regional_indicator_p:',
    'R': ':regional_indicator_r:',
    'S': ':regional_indicator_s:',
    'Ş': ':regional_indicator_ş:',
    'T': ':regional_indicator_t:',
    'U': ':regional_indicator_u:',
    'Ü': ':regional_indicator_u:',
    'V': ':regional_indicator_v:',
    'Y': ':regional_indicator_y:',
    'Z': ':regional_indicator_z:',
    'Q': ':regional_indicator_q:',
    'W': ':regional_indicator_w:',
    'X': ':regional_indicator_x:',
  
  
/** 'a': '🅰',
    'b': '🅱',
    'c': '🅲',
    'ç': '🅲',
    'd': '🅳',
    'e': '🅴',
    'f': '🅵',
    'g': '🅶',
    'ğ': '🅶',
    'h': '🅷',
    'ı': '🅸',
    'i': '🅸',
    'j': '🅹',
    'k': '🅺',
    'l': '🅻',
    'm': '🅼',
    'n': '🅽',
    'o': '🅾',
    'ö': '🅾',
    'p': '🅿',
    'r': '🆁',
    's': '🆂',
    'ş': '🆂',
    't': '🆃',
    'u': '🆄',
    'ü': '🆄',
    'v': '🆅',
    'y': '🆈',
    'z': '🆉',
    'q': '🆀',
    'w': '🆆',
    'x': '🆇',
    
:regional_indicator_a: :regional_indicator_b: :regional_indicator_c:  :regional_indicator_d:  :regional_indicator_e:  :regional_indicator_f:  :regional_indicator_g:  :regional_indicator_h:  :regional_indicator_i:  :regional_indicator_j:  :regional_indicator_k:  :regional_indicator_l:  :regional_indicator_m:  :regional_indicator_n:  :regional_indicator_o:  :regional_indicator_p:  :regional_indicator_r:  :regional_indicator_s:  :regional_indicator_t:  :regional_indicator_u:  :regional_indicator_v:  :regional_indicator_y:  :regional_indicator_z:  :regional_indicator_q:  :regional_indicator_w:  :regional_indicator_x: 
      //CAPSLOCK
    'A': '🅰',
    'B': '🅱',
    'C': '🅲',
    'Ç': '🅲',
    'D': '🅳',
    'E': '🅴',
    'F': '🅵',
    'G': '🅶',
    'Ğ': '🅶',
    'H': '🅷',
    'I': '🅸',
    'İ': '🅸',
    'J': '🅹',
    'K': '🅺',
    'L': '🅻',
    'M': '🅼',
    'N': '🅽',
    'O': '🅾',
    'Ö': '🅾',
    'P': '🅿',
    'R': '🆁',
    'S': '🆂',
    'Ş': '🆂',
    'T': '🆃',
    'U': '🆄',
    'Ü': '🆄',
    'V': '🆅',
    'Y': '🆈',
    'Z': '🆉',
    'Q': '🆀',
    'W': '🆆',
    'X': '🆇',
  **/
};


exports.run = function(client, message, args) {

	if (args.length < 1) return message.reply('Lütfen bir mesaj belirt. [Örn :  no.emojiyazı <mesaj>]')
  let user = message.author.id
  message.delete(5000)
	message.channel.send(args.join(' ').split('').map(c => mapping[c] || c).join(' ')).then(msg => msg.delete(5000));


};

exports.conf = {
  enabled: true, 
  guildOnly: true, 
  aliases: [],
  permLevel: 0 
};

exports.help = {
  name: 'emojiyazı', 
  description: 'Mesajınızı emoji haline getirir',
  usage: 'emojiyazı <mesaj>'
};